# Use postgres/example user/password credentials

services:

  oltp-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: trans_oltp

    volumes:
      - ./sql/oltp:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d trans-oltp" ]
      interval: 10s
      retries: 5
      timeout: 5s


  olap-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 1024mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: trans_olap

    volumes:
      - ./sql/olap:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d trans-olap" ]
      interval: 10s
      retries: 5
      timeout: 5s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: